CREATE DATABASE IF NOT EXISTS INVESTMENT_DATA_HUB_DEMO;

CREATE SCHEMA IF NOT EXISTS INVESTMENT_DATA_HUB_DEMO.BRONZE;
CREATE SCHEMA IF NOT EXISTS INVESTMENT_DATA_HUB_DEMO.ODS;
CREATE SCHEMA IF NOT EXISTS INVESTMENT_DATA_HUB_DEMO.CONTROL;
