-- AUTO-GENERATED from docs/csv_headers_inventory.csv
-- BRONZE tables: land raw CSV columns as STRING + add minimal load metadata

CREATE OR REPLACE TABLE BRONZE.FUND_MASTER (
  RUN_ID STRING,
  SOURCE_SYSTEM STRING,
  FUND_ID STRING,
  FUND_NAME STRING,
  BASE_CURRENCY STRING,
  INCEPTION_DATE STRING,
  ACCOUNTING_BASIS STRING,
  RAW_FILE_NAME STRING,
  LOADED_AT TIMESTAMP_NTZ
);

CREATE OR REPLACE TABLE BRONZE.FX_RATES (
  RUN_ID STRING,
  SOURCE_SYSTEM STRING,
  FX_DATE STRING,
  FROM_CCY STRING,
  TO_CCY STRING,
  FX_RATE STRING,
  RAW_FILE_NAME STRING,
  LOADED_AT TIMESTAMP_NTZ
);

CREATE OR REPLACE TABLE BRONZE.PRICE_TIMESERIES (
  RUN_ID STRING,
  SOURCE_SYSTEM STRING,
  PRICE_DATE STRING,
  ASSET_ID STRING,
  PRICE STRING,
  PRICE_CCY STRING,
  RAW_FILE_NAME STRING,
  LOADED_AT TIMESTAMP_NTZ
);

CREATE OR REPLACE TABLE BRONZE.SECURITY_MASTER (
  RUN_ID STRING,
  SOURCE_SYSTEM STRING,
  ASSET_ID STRING,
  ASSET_TYPE STRING,
  CURRENCY STRING,
  ID_ISIN STRING,
  ISSUE_DATE STRING,
  MATURITY_DATE STRING,
  TICKER STRING,
  COUPON_RATE STRING,
  PAY_FREQ STRING,
  DAY_COUNT STRING,
  RESET_FREQUENCY STRING,
  INDEX_NAME STRING,
  UNDERLYING STRING,
  STRIKE STRING,
  RAW_FILE_NAME STRING,
  LOADED_AT TIMESTAMP_NTZ
);

CREATE OR REPLACE TABLE BRONZE.TRADE (
  RUN_ID STRING,
  SOURCE_SYSTEM STRING,
  SOURCE_TXN_ID STRING,
  FUND_ID STRING,
  ASSET_ID STRING,
  TXN_TYPE STRING,
  TXN_DATE STRING,
  SETTLE_DATE STRING,
  QUANTITY STRING,
  PRICE STRING,
  CURRENCY STRING,
  RAW_FILE_NAME STRING,
  LOADED_AT TIMESTAMP_NTZ
);
